### ISSUE TITLE
GPU sample black screen

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#105]
I tried GPU sample with different configurations and i still get black screen, i tried to boot it on:

- old 3DS GW emuNand 9.4 as CIA
- old 3DS 4.5 sysNand Ninjhax
- old 3DS 6.1 sysNand as CIA with emuNand 9.5

Are there some limitations on compatible firmwares?

**Comment by fincs** [comment]
I can report that on old 3DS 9.2 sysNAND ninjhax it works.

**Comment by xerpi** [comment]
Same problem here with Old 3DS CFW 4.5.

**Comment by filfat** [comment]
Works for me on N3DS 9.0 Sysnand

**Comment by Steveice10** [comment]
Same problem here with old3DS + 4.5 + Ninjhax. My own GPU code works fine, but the ctrulib GPU example freezes on a black screen.

**Comment by Rinnegatamante** [comment]
Your GPU code works on 4.5 ninjhax? Can you post it somewhere?

**Comment by Lectem** [comment]
I confirm that it does work for ninjhax on old3ds 9.2 sysnand

**Comment by Steveice10** [comment]
Rinnegatamante: https://github.com/Steveice10/ctrcommon/blob/master/source/ctrcommon/gpu.cpp

**Comment by Rinnegatamante** [comment]
@Steveice10 Can you post a simple working sample for your GPU code?

**Comment by Steveice10** [comment]
@Rinnegatamante https://github.com/Steveice10/Nestopia3DS/blob/master/source/main.cpp

Do note that I'm still working out a few issues in my GPU code. Certain texture copies (when the width of the source buffer and destination texture aren't the same, I believe) don't work right, which also affects viewport changing. Also, buffers passed to the texture data function must be linearAlloc'd, which I hope to not require eventually since I want those details to be internal.

Anyway, this is a bit off topic to the issue. Should get back to the issue at hand.

**Comment by Steveice10** [comment]
This should fix the issue: https://github.com/smealum/ctrulib/pull/109

**Comment by WinterMute** [comment]
@Rinnegatamante I managed to dig out my 6.3 3DS and check @Steveice10's fix works there. Can you verify your 4.5 and 6.1 are now working?

**Comment by Rinnegatamante** [comment]
Yes, now works fine ;)

**Comment by WinterMute** [comment]
awesome, thanks @Steveice10
