### ISSUE TITLE
ndsp incompatibility (?) issues

### ISSUE THREAD

**Issue by Rinnegatamante** [smealum/ctrulib#209]
Another problem came with ndsp. After finishing adapting all my codes from csnd to dsp and checking all the functions work fine on a simple test script, i tried to use the new 3dsx file with Sunshell and this is the result: https://www.youtube.com/watch?v=MYZD5By1RUE

The issues came also on NH 1.1B:

1) Flickering screen
2) Slowed audio
3) Crackling audio
4) Crash (on NH 1.1b) / Freeze (on NH 2.5) after a bit

**Comment by Lectem** [comment]
Could be a scheduling problem with the sound thread, or simply bad timing :/
I did experiment the crackling audio too

**Comment by fincs** [comment]
From that video I can tell that whatever drawing code/logic code you are using is slow - I see how the screen flickers. As it turns out, the DSP needs to sync with the CPU every 160/32728 seconds. If the CPU is too busy, the DSP will be locked up, waiting for the CPU to give it a "It's OK to continue" signal. Maybe you should try optimizing your code. Additionally, last time I checked OGG decoding is very resource intensive, so that may also have something to do.

**Comment by fincs** [comment]
From what I can tell, it looks like your screen/drawing code is very slow - I see that in the video the screen flickers. As it is designed by Nintendo, the DSP needs to sync with the CPU every 160/32728 seconds. Otherwise, the DSP locks up waiting for the CPU to send it a "It's OK to continue" signal. Maybe you should try optimizing your code. Additionally, from tests I once did, OGG decoding is very resource intensive, so that may also have something to do with it.

Or you can try cheating (:smiling_imp:) and use `osSetSpeedupEnable(true)` to take advantage of the N3DS' 804MHz CPU.

**Comment by Rinnegatamante** [comment]
The problem appears also with wav files. Also Sunshell v.0.3.8 is using sf2dlib as drawing lib (so GPU rendering). It should be speed enough to not cause such problems i think.

**Comment by ihaveamac** [comment]
Tried the same .wav file in the video (samplerate of 32000) but with CPU speedup: crackling still exists in playback, but the song played for longer (about 34-36 seconds).

**Comment by Rinnegatamante** [comment]
I've tried to use dsp::DSP also in CHMM2 and the audio is iper-choppy. Could it be caused on the amount of samples given to dsp service or it is just an overloading issue?
I can also give you a test version with all set up just to test the result.

**Comment by Lectem** [comment]
How many samples per wavebuffer do you send?

Le sam. 12 déc. 2015 11:00, Rinnegatamante <notifications@github.com> a
écrit :

**Comment by Rinnegatamante** [comment]
In the case of CHMM2, the entire song is sent with a single wavebuffer:

createDspBlock(waveBuf, src->bytepersample, src->size, loop, (u32*)src->audiobuf);
	src->blocks = NULL;
	populatePurgeTable(src, waveBuf);
	ndspChnWaveBufAdd(ch, waveBuf);

**Comment by Lectem** [comment]
What is the samplerate ? Did you flush the buffer ?
I did experience some problems with choppy sound too, I think it might be a scheduling problem with the sound thread.

**Comment by Rinnegatamante** [comment]
Samplerate is 24000.
Yes i flush the buffer when i call createDspBlock:

// createDspBlock: Create a new block for DSP service
void createDspBlock(ndspWaveBuf* waveBuf, u16 bps, u32 size, bool loop, u32* data){
	waveBuf->data_vaddr = (void*)data;
	waveBuf->nsamples = size / bps;
	waveBuf->looping = loop;
	waveBuf->offset = 0;	
	DSP_FlushDataCache(data, size);
}

**Comment by Rinnegatamante** [comment]
I tried to add a svcSleepThread after ndspChnWaveBufAdd(ch, waveBuf); that just freezes the homebrew and now audio is perfect. Could it be related to GPU usage? (I'm currently using sf2dlib for graphics stuffs)

**Comment by profi200** [comment]
Sounds like a threading problem. The main thread causes too much CPU load and gives the DSP thread no chance to run properly.

**Comment by Rinnegatamante** [comment]
I partially solved (at least for CHMM2) by running sound thread on appcore ( https://github.com/smealum/ctrulib/blob/great-refactor/libctru/source/ndsp/ndsp.c#L487 changed this from -2 to 1 and priority from 0x31 to 0x18) but i don't know if it can be applied to lpp-3ds in general (cause lpp-3ds uses a secondary thread on appcore too for audio streaming purposes).
Anyway looks like the issue could be closed (?) .
