### ISSUE TITLE
Suspending an app in 2D mode results in incorrect display in home menu

### ISSUE THREAD

**Issue by flarn2006** [smealum/ctrulib#303]
I'm surprised this issue hasn't been reported here yet, as it's pretty hard to miss.

First, open a homebrew application that's installed as a CIA, specifically one that does **not** use 3D mode. I've never noticed a 2D homebrew app that doesn't exhibit this issue, but you probably have FBI if you're using CIA's, and FBI has the issue, so use that if you're unsure. Note that you should not use CTRXplorer as, despite not using 3D, this app actually does run in 3D mode, perhaps to avoid this issue.

Next, press HOME to suspend the app.

Now here's where the bug occurs. When the system displays the home menu, it will turn on 3D mode, as it should, and display the screenshot of the suspended app on the top screen with the curvature effect. However, the image will only be visible on the left eye. The right eye will see solid black, or if it uses the new "Homebrew" logo screen, that will appear.

Obviously, since the app isn't running in 3D mode, it only renders one image instead of two. However, it seems that when this happens the home menu doesn't just display that one image for both eyes. It still looks in the right eye's framebuffer or whatever it is for an image, and displays that. Most likely the application is responsible for copying the image over. Perhaps this is something that should be done in `aptMainLoop`?

**Comment by Cruel** [comment]
Unless there's some flag in the system or something that handles this (and there's nothing known form what I can see), I'd say this should be fixed by the application by writing to both top framebuffers. Having ctrulib copy framebuffers automatically when not in 3D mode is giving away too much control.

**Comment by esoteric-programmer** [comment]
The detection for 3D being enabled seems to be wrong: https://github.com/smealum/ctrulib/blob/bd34fd59dbf0691e2dba76be65f260303d8ccec7/libctru/source/services/apt.c#L155
The pointers seem to be different, even if 3D is disabled. Maybe it's a problem with double buffering.
However, if 3D is enabled, bit 5 of gspcapinfo.screencapture[0].format seems to be set. Otherwise, bit 6 seems to be set.
So, replacing the line mentioned above by
`capinfo->is3D = (gspcapinfo.screencapture[0].format & 0x20) != 0;`
(or something similar) seems to solve the issue without copying any framebuffers.
