### ISSUE TITLE
linearAlloc overwrites Citro3D texture

### ISSUE THREAD

**Issue by StuntHacks** [smealum/ctrulib#413]
When allocating an audio-buffer using linearAlloc, the function seems to allocate space already used by a Citro3D texture.
I allocate the buffer using this:
`u32 *audioBuffer = (u32*) linearAlloc(SAMPLESPERBUF * BYTESPERSAMPLE * 2);`

When I run the function that fills this buffer and plays the sound, a part of a drawn Citro2D-sprite becomes a scrambled mess of pixels which I assume is the content of the buffer.

This happens no matter if I run the function normally or multi-threaded.

**Comment by fincs** [comment]
You're very likely overflowing said buffer when you run the function that fills the buffer.

**Comment by StuntHacks** [comment]
Update: I tried just allocating the buffer and then filling it with useless data, and it still overwrites the texture.
```cpp
u32 *audioBuffer = (u32*) linearAlloc(SAMPLESPERBUF * BYTESPERSAMPLE * 2);
memset(audioBuffer, '-', SAMPLESPERBUF * BYTESPERSAMPLE * 2);
```

**Comment by fincs** [comment]
What are the values of SAMPLESPERBUF and BYTESPERSAMPLE?

**Comment by fincs** [comment]
The way you've chosen to convert graphics is very wasteful, not to mention the fact that you're manually converting graphics at runtime, which is resource intensive and redundant since tex3ds exists and it allows you to convert textures during the build process instead. In addition, you're storing unswizzled graphics inside the actual texture memory (albeit temporarily), and wasting time on swizzling it into a different buffer then copying it back. You should create a single staging buffer separate from the texture, decompress the texture there and then have tileTexture32 swizzle it directly into the actual texture memory.

In Sprite::setTexture, you're creating the C2D_Image with a static Tex3DS_SubTexture object that is *the same for every single sprite because it is a static variable*. As soon as you call setTexture again, the old subtexture will be *overwritten* with the values corresponding to the new texture. The subtexture object should be a member field of the Sprite class.

**Comment by StuntHacks** [comment]
I actually noticed the problem with the static SubTexture already and I already fixed that, I just didn't push it yet. However, that doesn't fix the problem either.
I'll try using tex3ds for texture conversion, maybe that'll help (and if not, it'll at least become way faster)

**Comment by Pirater12** [comment]
Can confirm. I got a similar issue in the past while using citro3d, where a texture kept on overwriting a previous texture.

**Comment by fincs** [comment]
Closing because this issue strongly smells of user error. A certain user had a similar bug in the past, and after many weeks of intense debugging it was discovered that in fact a buffer overrun was present in the code; after fixing that all issues disappeared.
